apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: patrickoceandigital/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: customer_database
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
      imagePullSecrets:
        - name: secretdockerhub

---

apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  ports:
    - name: backendport
      port: 60
      targetPort: 8080
  type: ClusterIP
  selector:
    app: backend